chore: fix

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -42,6 +42,9 @@ chmod +x "$BUILD_DIR/.profile.d/heroku-cli.sh"
 "$BUILD_DIR/.heroku/bin/heroku" version
 puts_step "Heroku CLI installation done"
 
+
+#sh scripts
+
 # Indentation
 indent()     { sed 's/^/       /'; }
 arrow()      { sed 's/^/-----> /'; }
@@ -103,3 +106,30 @@ for BUILDPACK_RUN_CMD in ${BUILDPACK_RUN_COMMANDS[@]}; do
     exit 1
   }
 done
+
+$BUILD_DIR/.heroku/bin/heroku config -s -a $HEROKU_APP_NAME > $BUILD_DIR/bin/envvars
+
+# other script
+
+# Fail fast and fail hard.
+set -eo pipefail
+
+
+BP_DIR=$(cd $(dirname $0); cd ..; pwd)
+BUILD_DIR=$1
+CACHE_DIR=$2
+ENV_DIR=$3
+
+
+indent() {
+  sed -u 's/^/       /'
+}
+
+
+
+echo 'Running `bin/envvars` inside the buildpack environment' | indent
+source $BUILD_DIR/bin/envvars
+
+# give environment to later buildpacks
+touch "$BP_DIR/export"
+export | grep -E -e ' (PATH|LD_PRELOAD|LD_LIBRARY_PATH|LIBRARY_PATH|INCLUDE_PATH|CPATH|CPPPATH|PKG_CONFIG_PATH)='  >> "$BP_DIR/export"
